package model;

import java.util.List;
import java.util.ArrayList;

//Represents a class containing player name,
//list of lands owned by player, and amount of money player has.
public class Player {
    private String name;
    private List<Land> lands;
    private int money;

    /* Requires: playerName has non-Zero length
     * Effects: name is set to player name, money is set to initial money,
     *          lands is an empty list of land.
     */
    public Player(String playerName, int initialMoney) {
        name = playerName;
        lands = new ArrayList<>();
        money = initialMoney;
    }

    // Effects: create new land object
    public Land createLand(int i) {
        return new Land(i);
    }


    //Modifies: this
    //Effects: add new land to player's land list, deduct land cost from money
    public void purchaseLand(Land land) {
        lands.add(land);
        money -= land.getCost();

    }

    //Modifies: this
    //Effects: set corp to one land in land list that doesn't have a corp and return true,
    //         if land list all have corp, return false
    public boolean plantCorp(Corp corp) {
        boolean hasEmptyLand = false;
        for (Land l : lands) {
            if (l.getPlant() == null) {
                l.setPlant(corp);
                hasEmptyLand = true;
                break;
            }
        }
        return hasEmptyLand;
    }

    //Modifies: this
    //Effects: add all land profit generated by the player's land list to money
    public void getProfit() {
        for (Land l : lands) {
            if (l.getPlant() != null) {
                money += l.getLandProfit();
            }
        }
    }

    public String getName() {
        return name;
    }

    public int getMoney() {
        return money;
    }

    public List<Land> getLands() {
        return lands;
    }

}
